### ISSUE TITLE
no DCS installation found

### ISSUE THREAD

**Issue by 132nd-Entropy** [132nd-etcher/EMFT#15]
version 0.4.1 unable to select active DCS installation 
suggestion: add the option to browse to the installation

**Comment by 132nd-etcher** [comment]
Thx for the feedback !

Could you use the "Send log" button on the "Log" tab, so I can look into the issue ?

**Comment by 132nd-etcher** [comment]
Is this still an issue for you?

**Comment by 132nd-Entropy** [comment]
no, no issue! thanks :D
